In [2]:
import pandas as pd

data = pd.read_csv('mlb_2016.csv')

In [3]:
original_df = data.copy()
df = data.drop(columns='Unnamed: 0')
df.head()

,attendance,away_team,away_team_errors,away_team_hits,away_team_runs,date,field_type,game_type,home_team,home_team_errors,...,temperature,wind_speed,wind_direction,sky,total_runs,game_hours_dec,season,home_team_win,home_team_loss,home_team_outcome
0,40030.0,New York Mets,1,7,3,2016-04-03,on grass,Night Game,Kansas City Royals,0,...,74.0,14.0,from Right to Left,Sunny,7,3.216667,regular season,1,0,Win
1,21621.0,Philadelphia Phillies,0,5,2,2016-04-06,on grass,Night Game,Cincinnati Reds,0,...,55.0,24.0,from Right to Left,Overcast,5,2.383333,regular season,1,0,Win
2,12622.0,Minnesota Twins,0,5,2,2016-04-06,on grass,Night Game,Baltimore Orioles,0,...,48.0,7.0,out to Leftfield,Unknown,6,3.183333,regular season,1,0,Win
3,18531.0,Washington Nationals,0,8,3,2016-04-06,on grass,Night Game,Atlanta Braves,1,...,65.0,10.0,from Right to Left,Cloudy,4,2.883333,regular season,0,1,Loss
4,18572.0,Colorado Rockies,1,8,4,2016-04-06,on grass,Day Game,Arizona Diamondbacks,0,...,77.0,0.0,in unknown direction,In Dome,7,2.650000,regular season,0,1,Loss

In [4]:
import numpy as np
display(df.info())
display(df.isnull().any())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2463 entries, 0 to 2462
Data columns (total 25 columns):
attendance           2460 non-null float64
away_team            2463 non-null object
away_team_errors     2463 non-null int64
away_team_hits       2463 non-null int64
away_team_runs       2463 non-null int64
date                 2463 non-null object
field_type           2463 non-null object
game_type            2463 non-null object
home_team            2463 non-null object
home_team_errors     2463 non-null int64
home_team_hits       2463 non-null int64
home_team_runs       2463 non-null int64
start_time           2463 non-null object
venue                2463 non-null object
day_of_week          2463 non-null object
temperature          2463 non-null float64
wind_speed           2463 non-null float64
wind_direction       2463 non-null object
sky                  2463 non-null object
total_runs           2463 non-null int64
game_hours_dec       2463 non-null float64
season               2463 non-null object
home_team_win        2463 non-null int64
home_team_loss       2463 non-null int64
home_team_outcome    2463 non-null object
dtypes: float64(4), int64(9), object(12)
memory usage: 481.1+ KB

None

attendance            True
away_team            False
away_team_errors     False
away_team_hits       False
away_team_runs       False
date                 False
field_type           False
game_type            False
home_team            False
home_team_errors     False
home_team_hits       False
home_team_runs       False
start_time           False
venue                False
day_of_week          False
temperature          False
wind_speed           False
wind_direction       False
sky                  False
total_runs           False
game_hours_dec       False
season               False
home_team_win        False
home_team_loss       False
home_team_outcome    False
dtype: bool

In [5]:
df = df.dropna()

In [6]:
matches = df.shape[0]
features = df.shape[1]-1
home_wins = len(df[df.home_team_outcome == 'Win'])
home_rate = home_wins / matches *100

print(f'No. of Matches:{matches}')
print(f'No of features:{features}')
print(f'Np. of Home Wins:{home_wins}')
print(f'Home Winning Rate:{"%.2f"%home_rate}%')

No. of Matches:2460
No of features:24
Np. of Home Wins:1302
Home Winning Rate:52.93%

In [7]:
home_teams = df.groupby('home_team').agg({'away_team_errors':'sum','away_team_hits':'sum','away_team_runs':'sum','home_team_errors':'sum',
                                          'home_team_hits':'sum','home_team_runs':'sum','total_runs':'sum','game_hours_dec':'sum','home_team_win':'sum',
                                          'home_team_loss':'sum','attendance':'mean','temperature':'mean','wind_speed':'mean',
                                          'game_hours_dec':'mean'}).reset_index().rename({'attendance':'avg_attendance',
                                                                                          'temperature':'avg_temp','wind_speed':'avg_wind_speed',
                                                                                          'game_hours_dec':'avg_game_duration'})
away_teams = df.groupby('away_team').agg({'away_team_errors':'sum','away_team_hits':'sum','away_team_runs':'sum','home_team_errors':'sum',
                                          'home_team_hits':'sum','home_team_runs':'sum','total_runs':'sum','game_hours_dec':'sum','home_team_win':'sum',
                                          'home_team_loss':'sum','attendance':'mean','temperature':'mean','wind_speed':'mean',
                                          'game_hours_dec':'mean'}).reset_index().rename({'attendance':'avg_attendance',
                                                                                          'temperature':'avg_temp','wind_speed':'avg_wind_speed',
                                                                                          'game_hours_dec':'avg_game_duration'})

In [8]:
home_teams.head()

,home_team,away_team_errors,away_team_hits,away_team_runs,home_team_errors,home_team_hits,home_team_runs,total_runs,game_hours_dec,home_team_win,home_team_loss,attendance,temperature,wind_speed
0,Arizona Diamondbacks,50,855,493,42,765,411,904,3.284362,33,48,25138.469136,81.074074,2.469136
1,Atlanta Braves,58,712,404,60,712,335,739,3.205144,31,50,24949.555556,81.308642,8.370370
2,Baltimore Orioles,42,699,336,39,688,376,712,2.977572,50,31,26819.061728,74.037037,5.061728
3,Boston Red Sox,50,741,384,40,853,480,864,3.271545,47,35,36523.951220,69.743902,12.256098
4,Chicago Cubs,45,596,264,53,723,413,677,3.064981,62,27,40103.662921,69.134831,8.741573

In [10]:
home_teams.corr()

,away_team_errors,away_team_hits,away_team_runs,home_team_errors,home_team_hits,home_team_runs,total_runs,game_hours_dec,home_team_win,home_team_loss,attendance,temperature,wind_speed
away_team_errors,1.000000,0.238957,0.217966,0.108779,0.429229,0.291840,0.309057,0.343979,0.097446,-0.027514,0.147730,0.283427,0.001352
away_team_hits,0.238957,1.000000,0.928416,0.449132,0.463430,0.375891,0.791111,0.313485,-0.427701,0.446611,-0.194328,0.267362,0.128726
away_team_runs,0.217966,0.928416,1.000000,0.524583,0.427286,0.360155,0.825020,0.368514,-0.506284,0.535685,-0.249735,0.352616,0.070285
home_team_errors,0.108779,0.449132,0.524583,1.000000,-0.070765,-0.058676,0.282802,0.039401,-0.411562,0.470428,-0.247524,0.258528,0.162994
home_team_hits,0.429229,0.463430,0.427286,-0.070765,1.000000,0.930126,0.822729,0.497602,0.381553,-0.332276,0.269905,0.060684,0.266455
home_team_runs,0.291840,0.375891,0.360155,-0.058676,0.930126,1.000000,0.824316,0.465714,0.525068,-0.469325,0.347782,0.042945,0.197562
total_runs,0.309057,0.791111,0.825020,0.282802,0.822729,0.824316,1.000000,0.505742,0.010821,0.040788,0.059117,0.240001,0.162327
game_hours_dec,0.343979,0.313485,0.368514,0.039401,0.497602,0.465714,0.505742,1.000000,-0.052061,0.088060,0.167270,0.206348,0.065029
home_team_win,0.097446,-0.427701,-0.506284,-0.411562,0.381553,0.525068,0.010821,-0.052061,1.000000,-0.964640,0.496322,-0.118085,0.162639
home_team_loss,-0.027514,0.446611,0.535685,0.470428,-0.332276,-0.469325,0.040788,0.088060,-0.964640,1.000000,-0.479312,0.082177,-0.135957
attendance,0.147730,-0.194328,-0.249735,-0.247524,0.269905,0.347782,0.059117,0.167270,0.496322,-0.479312,1.000000,-0.078798,0.292539
temperature,0.283427,0.267362,0.352616,0.258528,0.060684,0.042945,0.240001,0.206348,-0.118085,0.082177,-0.078798,1.000000,-0.236840
wind_speed,0.001352,0.128726,0.070285,0.162994,0.266455,0.197562,0.162327,0.065029,0.162639,-0.135957,0.292539,-0.236840,1.000000

In [11]:
away_teams.corr()

,away_team_errors,away_team_hits,away_team_runs,home_team_errors,home_team_hits,home_team_runs,total_runs,game_hours_dec,home_team_win,home_team_loss,attendance,temperature,wind_speed
away_team_errors,1.000000,-0.186378,-0.075466,0.093621,0.189694,0.198742,0.088001,0.187982,0.348374,-0.248657,0.408902,0.336212,0.015189
away_team_hits,-0.186378,1.000000,0.668237,0.295009,-0.184150,-0.126980,0.450217,0.351603,-0.449575,0.519403,0.147375,-0.070789,0.123209
away_team_runs,-0.075466,0.668237,1.000000,0.242713,-0.202373,-0.190335,0.673503,0.348816,-0.526933,0.623262,0.351145,-0.107422,-0.120791
home_team_errors,0.093621,0.295009,0.242713,1.000000,-0.216324,0.001895,0.199678,0.203237,-0.242093,0.295760,0.092560,-0.048108,0.080190
home_team_hits,0.189694,-0.184150,-0.202373,-0.216324,1.000000,0.698671,0.360763,-0.134282,0.458012,-0.565188,-0.349534,0.092306,0.313596
home_team_runs,0.198742,-0.126980,-0.190335,0.001895,0.698671,1.000000,0.597480,-0.022656,0.683954,-0.683918,-0.057449,0.134289,0.216813
total_runs,0.088001,0.450217,0.673503,0.199678,0.360763,0.597480,1.000000,0.267859,0.084575,-0.005865,0.243565,0.013369,0.064585
game_hours_dec,0.187982,0.351603,0.348816,0.203237,-0.134282,-0.022656,0.267859,1.000000,-0.128034,0.247234,0.481297,0.238597,0.126807
home_team_win,0.348374,-0.449575,-0.526933,-0.242093,0.458012,0.683954,0.084575,-0.128034,1.000000,-0.937846,-0.065484,0.077370,0.078314
home_team_loss,-0.248657,0.519403,0.623262,0.295760,-0.565188,-0.683918,-0.005865,0.247234,-0.937846,1.000000,0.240632,-0.161274,-0.136089
attendance,0.408902,0.147375,0.351145,0.092560,-0.349534,-0.057449,0.243565,0.481297,-0.065484,0.240632,1.000000,0.151118,-0.198943
temperature,0.336212,-0.070789,-0.107422,-0.048108,0.092306,0.134289,0.013369,0.238597,0.077370,-0.161274,0.151118,1.000000,-0.005119
wind_speed,0.015189,0.123209,-0.120791,0.080190,0.313596,0.216813,0.064585,0.126807,0.078314,-0.136089,-0.198943,-0.005119,1.000000

In [12]:
target = df['home_team_win']
features = df.drop(['home_team_win','home_team_outcome','home_team_loss','home_team_runs','away_team_runs','total_runs','away_team_errors','away_team_hits','home_team_hits','home_team_errors'], axis=1)

In [13]:
display(target.head())
display(features.head())

0    1
1    1
2    1
3    0
4    0
Name: home_team_win, dtype: int64

,attendance,away_team,date,field_type,game_type,home_team,start_time,venue,day_of_week,temperature,wind_speed,wind_direction,sky,game_hours_dec,season
0,40030.0,New York Mets,2016-04-03,on grass,Night Game,Kansas City Royals,7:38 p.m. Local,Kauffman Stadium,Sunday,74.0,14.0,from Right to Left,Sunny,3.216667,regular season
1,21621.0,Philadelphia Phillies,2016-04-06,on grass,Night Game,Cincinnati Reds,7:11 p.m. Local,Great American Ball Park,Wednesday,55.0,24.0,from Right to Left,Overcast,2.383333,regular season
2,12622.0,Minnesota Twins,2016-04-06,on grass,Night Game,Baltimore Orioles,7:07 p.m. Local,Oriole Park at Camden Yards,Wednesday,48.0,7.0,out to Leftfield,Unknown,3.183333,regular season
3,18531.0,Washington Nationals,2016-04-06,on grass,Night Game,Atlanta Braves,7:10 p.m. Local,Turner Field,Wednesday,65.0,10.0,from Right to Left,Cloudy,2.883333,regular season
4,18572.0,Colorado Rockies,2016-04-06,on grass,Day Game,Arizona Diamondbacks,12:40 p.m. Local,Chase Field,Wednesday,77.0,0.0,in unknown direction,In Dome,2.650000,regular season

### Date Pre-Process

In [14]:
# Date Column Datatype Conversion 
features.date = features.date.astype('datetime64[ns]')
days_dict = {
        'Monday': 1,
        'Tuesday': 2,
        'Wednesday': 3,
        'Thursday': 4,
        'Friday': 5,
        'Saturday': 6,
        'Sunday': 7,
}

# Change week days to numbers
features.day_of_week = features.day_of_week.map(days_dict)

# Select the Month
features['Month'] = features.date.dt.month

In [16]:
df.date = df.date.astype('datetime64[ns]')
df['Week'] = df.date.dt.week

In [26]:
# home[home.home_team == 'Boston Red Sox'].plot(x='Week', y='home_team_runs',figsize=(20,7))
# away[away.away_team == 'Boston Red Sox'].plot(x='Month', y='home_team_runs',figsize=(20,7))
home = df[df.home_team == 'Boston Red Sox'].groupby('Week')['home_team_runs','home_team_errors'].sum()
away = df[df.away_team == 'Boston Red Sox'].groupby('Week')['away_team_runs','away_team_errors'].sum()
display(home)
display(away)

      home_team_runs  home_team_errors
Week
15                28                 0
16                18                 3
17                32                 2
19                73                 6
20                16                 3
21                20                 1
22                12                 1
24                21                 1
25                16                 4
26                17                 4
27                39                 4
29                46                 4
30                13                 0
32                42                 4
34                15                 1
35                20                 0
37                40                 1
39                 9                 1
41                 3                 0

      away_team_runs  away_team_errors
Week
14                28                 3
16                16                 2
17                12                 1
18                22                 0
20                11                 2
21                19                 3
22                29                 1
23                33                 3
25                13                 3
26                15                 2
28                11                 1
30                14                 2
31                24                 3
33                37                 2
34                12                 1
35                27                 2
36                39                 4
38                31                 0
39                 8                 0
40                 4                 1

In [24]:
test_runs = pd.concat([home, away.groupby(level=0).sum()], axis=1).fillna(0)
test_runs['Runs'] = test_runs.home_team_runs + test_runs.away_team_runs
test_runs['Errors'] = test_runs.home_team_errors + test_runs.away_team_errors

      home_team_runs  away_team_runs
Week
14               0.0            28.0
15              28.0             0.0
16              18.0            16.0
17              32.0            12.0
18               0.0            22.0
19              73.0             0.0
20              16.0            11.0
21              20.0            19.0
22              12.0            29.0
23               0.0            33.0
24              21.0             0.0
25              16.0            13.0
26              17.0            15.0
27              39.0             0.0
28               0.0            11.0
29              46.0             0.0
30              13.0            14.0
31               0.0            24.0
32              42.0             0.0
33               0.0            37.0
34              15.0            12.0
35              20.0            27.0
36               0.0            39.0
37              40.0             0.0
38               0.0            31.0
39               9.0             8.0
40               0.0             4.0
41               3.0             0.0

In [1]:
test_teams = ['Miami Marlins', 'Boston Red Sox']
home_series = df[df.home_team.isin(test_teams)].groupby(['Week','home_team']).sum()
away_series = df[df.away_team.isin(test_teams)].groupby('Week')['away_team_runs'].sum()
# home_series.plot(y='home_team_runs',figsize=(18,6))
home_series

NameError: name 'df' is not defined

In [105]:

# drop date column
features = features.drop('date', axis=1)

,attendance,away_team,field_type,game_type,home_team,start_time,venue,day_of_week,temperature,wind_speed,wind_direction,sky,game_hours_dec,season,home_team_win,Month,Year
0,40030.0,New York Mets,on grass,Night Game,Kansas City Royals,7:38 p.m. Local,Kauffman Stadium,NaN,74.0,14.0,from Right to Left,Sunny,3.216667,regular season,1,4,2016
1,21621.0,Philadelphia Phillies,on grass,Night Game,Cincinnati Reds,7:11 p.m. Local,Great American Ball Park,NaN,55.0,24.0,from Right to Left,Overcast,2.383333,regular season,1,4,2016
2,12622.0,Minnesota Twins,on grass,Night Game,Baltimore Orioles,7:07 p.m. Local,Oriole Park at Camden Yards,NaN,48.0,7.0,out to Leftfield,Unknown,3.183333,regular season,1,4,2016
3,18531.0,Washington Nationals,on grass,Night Game,Atlanta Braves,7:10 p.m. Local,Turner Field,NaN,65.0,10.0,from Right to Left,Cloudy,2.883333,regular season,0,4,2016
4,18572.0,Colorado Rockies,on grass,Day Game,Arizona Diamondbacks,12:40 p.m. Local,Chase Field,NaN,77.0,0.0,in unknown direction,In Dome,2.650000,regular season,0,4,2016
5,28386.0,Seattle Mariners,on grass,Night Game,Texas Rangers,7:07 p.m. Local,Globe Life Park in Arlington,NaN,81.0,12.0,from Right to Left,Cloudy,3.500000,regular season,0,4,2016
6,12757.0,Toronto Blue Jays,on turf,Night Game,Tampa Bay Rays,7:10 p.m. Local,Tropicana Field,NaN,72.0,0.0,in unknown direction,In Dome,3.116667,regular season,1,4,2016
7,28329.0,Los Angeles Dodgers,on grass,Night Game,San Diego Padres,7:11 p.m. Local,Petco Park,NaN,70.0,6.0,from Left to Right,Unknown,2.600000,regular season,0,4,2016
8,26049.0,St. Louis Cardinals,on grass,Night Game,Pittsburgh Pirates,7:08 p.m. Local,PNC Park,NaN,40.0,7.0,out to Leftfield,Sunny,3.450000,regular season,1,4,2016
9,10478.0,Chicago White Sox,on grass,Night Game,Oakland Athletics,7:08 p.m. Local,Oakland-Alameda County Coliseum,NaN,70.0,8.0,out to Rightfield,Cloudy,3.466667,regular season,0,4,2016
10,47820.0,Houston Astros,on grass,Day Game,New York Yankees,1:11 p.m. Local,Yankee Stadium III,NaN,36.0,18.0,from Left to Right,Sunny,3.283333,regular season,0,4,2016
11,24123.0,San Francisco Giants,on grass,Night Game,Milwaukee Brewers,7:10 p.m. Local,Miller Park,NaN,64.0,0.0,in unknown direction,In Dome,2.483333,regular season,0,4,2016
12,36911.0,Detroit Tigers,on grass,Night Game,Miami Marlins,7:37 p.m. Local,Marlins Park,NaN,77.0,16.0,from Left to Right,Sunny,3.783333,regular season,0,4,2016
13,13468.0,Texas Rangers,on grass,Night Game,Seattle Mariners,7:10 p.m. Local,Safeco Field,NaN,57.0,2.0,in from Leftfield,Unknown,3.000000,regular season,0,4,2016
14,45229.0,San Diego Padres,on grass,Day Game,Philadelphia Phillies,3:09 p.m. Local,Citizens Bank Park,NaN,66.0,17.0,out to Leftfield,Unknown,2.850000,regular season,0,4,2016
15,13371.0,Los Angeles Angels of Anaheim,on grass,Night Game,Oakland Athletics,7:07 p.m. Local,Oakland-Alameda County Coliseum,NaN,63.0,11.0,out to Rightfield,Cloudy,3.083333,regular season,0,4,2016
16,24318.0,Miami Marlins,on grass,Night Game,New York Mets,7:11 p.m. Local,Citi Field,NaN,57.0,15.0,out to Leftfield,Unknown,3.750000,regular season,0,4,2016
17,40638.0,Chicago White Sox,on grass,Day Game,Minnesota Twins,3:16 p.m. Local,Target Field,NaN,42.0,21.0,in from Leftfield,Cloudy,3.083333,regular season,0,4,2016
18,43332.0,Kansas City Royals,on grass,Night Game,Houston Astros,7:12 p.m. Local,Minute Maid Park,NaN,73.0,0.0,in unknown direction,In Dome,2.983333,regular season,1,4,2016
19,26271.0,Pittsburgh Pirates,on grass,Day Game,Detroit Tigers,1:10 p.m. Local,Comerica Park,NaN,56.0,9.0,in from Rightfield,Overcast,3.283333,regular season,0,4,2016
20,40882.0,Cincinnati Reds,on grass,Night Game,Chicago Cubs,7:06 p.m. Local,Wrigley Field,NaN,48.0,12.0,from Left to Right,Cloudy,3.050000,regular season,1,4,2016
21,21203.0,Kansas City Royals,on grass,Night Game,Houston Astros,7:11 p.m. Local,Minute Maid Park,NaN,75.0,2.0,out to Leftfield,Cloudy,2.683333,regular season,0,4,2016
22,21226.0,San Francisco Giants,on grass,Day Game,Colorado Rockies,1:10 p.m. Local,Coors Field,NaN,72.0,12.0,out to Centerfield,Cloudy,3.433333,regular season,1,4,2016
23,34898.0,Cincinnati Reds,on grass,Night Game,Chicago Cubs,7:05 p.m. Local,Wrigley Field,NaN,45.0,8.0,out to Centerfield,Sunny,3.116667,regular season,1,4,2016
24,19400.0,Atlanta Braves,on grass,Night Game,Washington Nationals,7:05 p.m. Local,Nationals Park,NaN,56.0,0.0,in unknown direction,Sunny,2.200000,regular season,1,4,2016
25,27938.0,New York Yankees,on turf,Night Game,Toronto Blue Jays,7:08 p.m. Local,Rogers Centre,NaN,68.0,0.0,in unknown direction,In Dome,2.716667,regular season,1,4,2016
26,16783.0,Toronto Blue Jays,on grass,Night Game,Baltimore Orioles,7:09 p.m. Local,Oriole Park at Camden Yards,NaN,69.0,11.0,in from Centerfield,Sunny,2.833333,regular season,0,4,2016
27,14160.0,Los Angeles Dodgers,on grass,Night Game,Atlanta Braves,7:10 p.m. Local,Turner Field,NaN,80.0,2.0,out to Centerfield,Unknown,2.950000,regular season,1,4,2016
28,45432.0,Chicago Cubs,on grass,Night Game,St. Louis Cardinals,7:09 p.m. Local,Busch Stadium III,NaN,75.0,15.0,from Right to Left,Unknown,2.533333,regular season,0,4,2016
29,41432.0,Arizona Diamondbacks,on grass,Night Game,San Francisco Giants,7:16 p.m. Local,AT&T Park,NaN,67.0,6.0,out to Centerfield,Cloudy,4.583333,regular season,0,4,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2433,30003.0,Houston Astros,on grass,Day Game,New York Yankees,4:17 p.m. Local,Yankee Stadium III,NaN,57.0,24.0,from Right to Left,Unknown,3.000000,regular season,1,4,2016
2434,10784.0,Philadelphia Phillies,on grass,Day Game,Cincinnati Reds,12:36 p.m. Local,Great American Ball Park,NaN,43.0,17.0,out to Leftfield,Overcast,3.066667,regular season,1,4,2016
2435,11142.0,Minnesota Twins,on grass,Night Game,Baltimore Orioles,7:07 p.m. Local,Oriole Park at Camden Yards,NaN,51.0,5.0,out to Centerfield,Cloudy,2.533333,regular season,1,4,2016
2436,24656.0,Chicago Cubs,on grass,Night Game,Arizona Diamondbacks,6:41 p.m. Local,Chase Field,NaN,79.0,0.0,in unknown direction,In Dome,3.483333,regular season,0,4,2016
2437,39089.0,Texas Rangers,on grass,Night Game,Los Angeles Angels of Anaheim,7:07 p.m. Local,Angel Stadium of Anaheim,NaN,64.0,4.0,out to Centerfield,Unknown,3.183333,regular season,1,4,2016
2438,26945.0,Seattle Mariners,on grass,Day Game,Texas Rangers,1:09 p.m. Local,Globe Life Park in Arlington,NaN,74.0,11.0,out to Centerfield,Sunny,2.933333,regular season,0,4,2016
2439,14257.0,Toronto Blue Jays,on turf,Day Game,Tampa Bay Rays,1:10 p.m. Local,Tropicana Field,NaN,72.0,0.0,in unknown direction,In Dome,2.783333,regular season,1,4,2016
2440,30054.0,Los Angeles Dodgers,on grass,Night Game,San Diego Padres,6:12 p.m. Local,Petco Park,NaN,65.0,7.0,in unknown direction,Overcast,2.950000,regular season,0,4,2016
2441,14890.0,St. Louis Cardinals,on grass,Night Game,Pittsburgh Pirates,7:10 p.m. Local,PNC Park,NaN,63.0,15.0,from Right to Left,Cloudy,3.133333,regular season,1,4,2016
2442,16468.0,Chicago White Sox,on grass,Night Game,Oakland Athletics,7:09 p.m. Local,Oakland-Alameda County Coliseum,NaN,83.0,0.0,in unknown direction,Cloudy,2.900000,regular season,1,4,2016
2443,37493.0,Houston Astros,on grass,Night Game,New York Yankees,7:08 p.m. Local,Yankee Stadium III,NaN,43.0,11.0,from Right to Left,Unknown,3.750000,regular season,1,4,2016
2444,39782.0,New York Mets,on grass,Day Game,Kansas City Royals,3:16 p.m. Local,Kauffman Stadium,NaN,68.0,17.0,from Right to Left,Sunny,2.850000,regular season,0,4,2016
2445,34493.0,Boston Red Sox,on grass,Day Game,Cleveland Indians,1:11 p.m. Local,Progressive Field,NaN,34.0,8.0,from Left to Right,Sunny,3.216667,regular season,0,4,2016
2446,21830.0,Colorado Rockies,on grass,Night Game,Arizona Diamondbacks,6:42 p.m. Local,Chase Field,NaN,89.0,4.0,out to Rightfield,Sunny,3.233333,regular season,1,4,2016
2447,37042.0,Chicago Cubs,on grass,Night Game,Los Angeles Angels of Anaheim,7:07 p.m. Local,Angel Stadium of Anaheim,NaN,76.0,8.0,from Right to Left,Unknown,2.566667,regular season,0,4,2016
2448,49289.0,Seattle Mariners,on grass,Day Game,Texas Rangers,3:09 p.m. Local,Globe Life Park in Arlington,NaN,83.0,4.0,in from Rightfield,Sunny,2.633333,regular season,1,4,2016
2449,15116.0,Toronto Blue Jays,on turf,Night Game,Tampa Bay Rays,7:10 p.m. Local,Tropicana Field,NaN,72.0,0.0,in unknown direction,In Dome,2.966667,regular season,0,4,2016
2450,44317.0,Los Angeles Dodgers,on grass,Day Game,San Diego Padres,4:11 p.m. Local,Petco Park,NaN,72.0,12.0,from Left to Right,Cloudy,3.166667,regular season,0,4,2016
2451,35067.0,Chicago White Sox,on grass,Night Game,Oakland Athletics,7:07 p.m. Local,Oakland-Alameda County Coliseum,NaN,65.0,5.0,out to Rightfield,Sunny,2.933333,regular season,0,4,2016
2452,44318.0,San Francisco Giants,on grass,Day Game,Milwaukee Brewers,1:11 p.m. Local,Miller Park,NaN,65.0,0.0,in unknown direction,In Dome,3.583333,regular season,0,4,2016
2453,43683.0,Philadelphia Phillies,on grass,Day Game,Cincinnati Reds,4:11 p.m. Local,Great American Ball Park,NaN,50.0,16.0,from Left to Right,Cloudy,2.933333,regular season,1,4,2016
2454,45785.0,Minnesota Twins,on grass,Day Game,Baltimore Orioles,4:46 p.m. Local,Oriole Park at Camden Yards,NaN,58.0,6.0,from Right to Left,Overcast,2.800000,regular season,1,4,2016
2455,48282.0,Washington Nationals,on grass,Day Game,Atlanta Braves,4:13 p.m. Local,Turner Field,NaN,75.0,11.0,from Left to Right,Sunny,3.383333,regular season,0,4,2016
2456,48165.0,Colorado Rockies,on grass,Night Game,Arizona Diamondbacks,6:42 p.m. Local,Chase Field,NaN,90.0,5.0,out to Rightfield,Cloudy,4.183333,regular season,0,4,2016
2457,44020.0,Chicago Cubs,on grass,Night Game,Los Angeles Angels of Anaheim,7:08 p.m. Local,Angel Stadium of Anaheim,NaN,75.0,6.0,out to Rightfield,Sunny,3.133333,regular season,0,4,2016
2458,31042.0,Toronto Blue Jays,on turf,Day Game,Tampa Bay Rays,4:09 p.m. Local,Tropicana Field,NaN,72.0,0.0,in unknown direction,In Dome,2.850000,regular season,0,4,2016
2459,39500.0,St. Louis Cardinals,on grass,Day Game,Pittsburgh Pirates,1:15 p.m. Local,PNC Park,NaN,39.0,14.0,out to Leftfield,Unknown,3.033333,regular season,1,4,2016
2460,20098.0,San Francisco Giants,on grass,Day Game,Milwaukee Brewers,12:41 p.m. Local,Miller Park,NaN,66.0,0.0,in unknown direction,In Dome,3.316667,regular season,1,4,2016
2461,17883.0,Detroit Tigers,on grass,Day Game,Miami Marlins,4:57 p.m. Local,Marlins Park,NaN,71.0,0.0,in unknown direction,In Dome,3.366667,regular season,0,4,2016
2462,10298.0,Boston Red Sox,on grass,Night Game,Cleveland Indians,6:22 p.m. Local,Progressive Field,NaN,60.0,7.0,out to Leftfield,Unknown,3.483333,regular season,1,4,2016

In [214]:
home_teams.mean()

away_team_errors       47.566667
away_team_hits        718.900000
away_team_runs        362.033333
home_team_errors       48.066667
home_team_hits        706.133333
home_team_runs        370.666667
total_runs            732.700000
game_hours_dec          3.085184
home_team_win          43.400000
home_team_loss         38.566667
attendance          30288.152524
temperature            73.834290
wind_speed              7.471576
dtype: float64

In [13]:
away_teams.mean()

away_team_errors       47.566667
away_team_hits        718.900000
away_team_runs        362.033333
home_team_errors       48.066667
home_team_hits        706.133333
home_team_runs        370.666667
total_runs            732.700000
game_hours_dec          3.084544
home_team_win          43.400000
home_team_loss         38.566667
attendance          30340.915754
temperature            73.820114
wind_speed              7.492091
dtype: float64

In [407]:
from baseball_scraper import batting_stats_range

batting_stats_range('2019-04-01','2019-04-14')

,Name,Age,#days,Lev,Tm,G,PA,AB,R,H,...,SH,SF,GDP,SB,CS,BA,OBP,SLG,OPS,mlb_ID
1,Jose Abreu,32,216,MLB-AL,Chicago,11,48,44,7,7,...,0,1,1,2,0,0.159,0.208,0.295,0.504,547989
2,Ronald Acuna Jr.,21,216,MLB-NL,Atlanta,12,54,43,12,14,...,0,0,2,1,0,0.326,0.442,0.744,1.186,660670
3,Willy Adames,23,216,MLB-AL,Tampa Bay,12,51,46,10,14,...,0,0,0,0,0,0.304,0.373,0.435,0.807,642715
4,Matt Adams,30,217,MLB-NL,Washington,9,16,15,0,3,...,0,1,1,0,0,0.200,0.188,0.333,0.521,571431
5,Ehire Adrianza,29,220,MLB-AL,Minnesota,6,18,15,3,2,...,0,1,0,0,0,0.133,0.222,0.133,0.356,501303
6,Jesus Aguilar,29,216,MLB-NL,Milwaukee,10,44,33,3,5,...,0,1,2,0,0,0.152,0.310,0.212,0.522,542583
7,Nick Ahmed,29,216,MLB-NL,Arizona,12,48,47,10,14,...,0,1,1,1,0,0.298,0.292,0.447,0.738,605113
8,Hanser Alberto,26,216,MLB-AL,Baltimore,11,39,38,1,10,...,0,0,0,0,0,0.263,0.282,0.289,0.572,593643
9,Ozzie Albies,22,216,MLB-NL,Atlanta,12,56,51,9,17,...,0,0,0,2,1,0.333,0.393,0.490,0.883,645277
10,Sandy Alcantara,23,218,MLB-NL,Miami,2,3,3,0,0,...,0,0,0,0,0,0.000,0.000,0.000,0.000,645261
11,Jorge Alfaro,26,217,MLB-NL,Miami,9,31,29,4,10,...,0,0,1,0,2,0.345,0.387,0.552,0.939,595751
12,Anthony Alford,24,228,MLB-AL,Toronto,1,3,3,0,0,...,0,0,0,0,0,0.000,0.000,0.000,0.000,546990
13,Cody Allen,30,217,MLB-AL,Los Angeles,1,1,1,0,0,...,0,0,0,0,0,0.000,0.000,0.000,0.000,592102
14,Greg Allen,26,216,MLB-AL,Cleveland,9,19,18,1,1,...,0,0,0,0,0,0.056,0.105,0.111,0.216,656185
15,Yency Almonte,25,223,MLB-NL,Colorado,1,1,1,0,0,...,0,0,0,0,0,0.000,0.000,0.000,0.000,622075
16,Albert Almora,25,217,MLB-NL,Chicago,11,29,28,2,7,...,0,0,0,2,0,0.250,0.276,0.250,0.526,546991
17,Pete Alonso,24,216,MLB-NL,New York,12,48,43,10,13,...,0,0,1,0,0,0.302,0.375,0.814,1.189,624413
18,Yonder Alonso,32,216,MLB-AL,Chicago,11,41,33,5,4,...,0,0,0,0,0,0.121,0.293,0.212,0.505,475174
19,Aaron Altherr,28,216,MLB-NL,Philadelphia,10,10,10,0,1,...,0,0,0,0,0,0.100,0.100,0.200,0.300,571437
20,Jose Altuve,29,216,MLB-AL,Houston,12,54,50,10,18,...,0,1,1,1,0,0.360,0.389,0.740,1.129,514888
21,Brian Anderson,26,216,MLB-NL,Miami,11,48,42,2,12,...,0,0,0,2,0,0.286,0.375,0.452,0.827,605119
22,Chase Anderson,31,225,MLB-NL,Milwaukee,1,1,1,0,0,...,0,0,0,0,0,0.000,0.000,0.000,0.000,502624
23,Tim Anderson,26,216,MLB-AL,Chicago,9,38,37,8,17,...,0,0,1,4,0,0.459,0.474,0.730,1.203,641313
24,Tyler Anderson,29,225,MLB-NL,Colorado,1,1,1,1,1,...,0,0,0,0,0,1.000,1.000,1.000,2.000,542881
25,Elvis Andrus,30,216,MLB-AL,Texas,11,46,45,6,18,...,0,0,0,4,0,0.400,0.413,0.644,1.057,462101
27,Chris Archer,30,217,MLB-NL,Pittsburgh,3,8,7,0,1,...,1,0,0,0,0,0.143,0.143,0.143,0.286,502042
28,Orlando Arcia,24,216,MLB-NL,Milwaukee,12,41,37,7,10,...,0,0,2,0,0,0.270,0.341,0.541,0.882,606115
29,Nolan Arenado,28,216,MLB-NL,Colorado,12,53,45,5,12,...,0,1,1,1,1,0.267,0.358,0.400,0.758,571448
30,Jake Arrieta,33,218,MLB-NL,Philadelphia,2,5,5,0,0,...,0,0,0,0,0,0.000,0.000,0.000,0.000,453562
31,Christian Arroyo,24,223,MLB-AL,Tampa Bay,4,9,9,0,3,...,0,0,0,0,0,0.333,0.333,0.333,0.667,624414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,Alex Verdugo,23,216,MLB-NL,Los Angeles,12,27,27,4,9,...,0,0,1,0,0,0.333,0.333,0.741,1.074,657077
510,Jonathan Villar,28,216,MLB-AL,Baltimore,13,57,54,10,17,...,0,0,1,1,1,0.315,0.351,0.556,0.906,542340
511,Daniel Vogelbach,26,216,MLB-AL,Seattle,9,39,33,8,14,...,0,1,0,0,0,0.424,0.487,1.091,1.578,596129
512,Luke Voit,28,216,MLB-AL,New York,12,50,44,7,8,...,0,0,1,0,0,0.182,0.280,0.409,0.689,572228
513,Joey Votto,35,216,MLB-NL,Cincinnati,12,48,41,8,9,...,0,0,1,0,0,0.220,0.333,0.366,0.699,458015
514,Michael Wacha,27,219,MLB-NL,St. Louis,2,3,2,0,0,...,1,0,0,0,0,0.000,0.000,0.000,0.000,608379
515,Tyler Wade,24,217,MLB-AL,New York,7,19,17,2,3,...,1,0,0,1,0,0.176,0.222,0.176,0.399,642180
516,Adam Wainwright,37,217,MLB-NL,St. Louis,3,6,5,0,1,...,0,0,0,0,0,0.200,0.333,0.200,0.533,425794
517,Marcus Walden,30,223,MLB-AL,Boston,1,1,1,0,0,...,0,0,0,0,0,0.000,0.000,0.000,0.000,519393
518,Christian Walker,28,216,MLB-NL,Arizona,12,45,40,5,8,...,0,0,0,0,0,0.200,0.289,0.425,0.714,572233
519,Neil Walker,33,216,MLB-NL,Miami,12,43,40,3,8,...,0,0,4,0,0,0.200,0.256,0.375,0.631,435522
521,Chad Wallach,27,216,MLB-NL,Miami,6,18,15,1,4,...,0,0,0,0,0,0.267,0.389,0.267,0.656,595453
522,Taylor Ward,25,217,MLB-AL,Los Angeles,3,6,6,0,1,...,0,0,0,0,0,0.167,0.167,0.333,0.500,621493
523,Luke Weaver,25,218,MLB-NL,Arizona,3,3,3,0,0,...,0,0,0,0,0,0.000,0.000,0.000,0.000,596133
524,Zack Wheeler,29,218,MLB-NL,New York,2,4,4,0,1,...,0,0,0,0,0,0.250,0.250,0.250,0.500,554430
525,Tyler White,28,218,MLB-AL,Houston,6,20,18,1,4,...,0,0,1,0,0,0.222,0.300,0.278,0.578,643603
526,Matt Wieters,33,219,MLB-NL,St. Louis,2,5,3,0,1,...,0,1,0,1,0,0.333,0.400,0.333,0.733,446308
527,Nick Williams,25,216,MLB-NL,Philadelphia,9,10,9,1,2,...,0,0,0,0,0,0.222,0.300,0.333,0.633,608384
528,Trevor Williams,27,218,MLB-NL,Pittsburgh,2,4,4,0,0,...,0,0,0,0,0,0.000,0.000,0.000,0.000,592866
529,Jesse Winker,25,216,MLB-NL,Cincinnati,12,42,38,7,8,...,0,0,0,0,1,0.211,0.286,0.526,0.812,608385
530,Patrick Wisdom,27,216,MLB-AL,Texas,4,15,14,1,2,...,1,0,0,0,0,0.143,0.143,0.143,0.286,621550
531,Tony Wolters,27,216,MLB-NL,Colorado,9,24,23,0,3,...,0,0,0,0,0,0.130,0.167,0.174,0.341,547172
532,Kolten Wong,28,216,MLB-NL,St. Louis,11,44,33,5,6,...,0,1,0,2,0,0.182,0.364,0.455,0.818,543939
533,Brandon Woodruff,26,225,MLB-NL,Milwaukee,1,2,1,1,1,...,0,0,0,0,0,1.000,1.000,1.000,2.000,605540
534,Kyle Wright,23,218,MLB-NL,Atlanta,2,3,3,0,0,...,0,0,0,0,0,0.000,0.000,0.000,0.000,657140
535,Christian Yelich,27,216,MLB-NL,Milwaukee,12,55,49,8,14,...,0,1,0,3,0,0.286,0.345,0.408,0.754,592885
536,Mark Zagunis,26,217,MLB-NL,Chicago,9,18,18,0,6,...,0,0,0,0,0,0.333,0.333,0.444,0.778,657145
537,Ryan Zimmerman,34,216,MLB-NL,Washington,10,40,32,4,7,...,0,1,1,0,0,0.219,0.350,0.313,0.663,475582
538,Ben Zobrist,38,217,MLB-NL,Chicago,9,33,28,2,9,...,0,0,1,0,0,0.321,0.424,0.321,0.746,450314
539,Mike Zunino,28,216,MLB-AL,Tampa Bay,9,36,34,3,6,...,0,0,0,0,0,0.176,0.222,0.294,0.516,572287

In [396]:
data.columns

Index(['Name', 'Age', '#days', 'Lev', 'Tm', 'G', 'PA', 'AB', 'R', 'H', '2B',
       '3B', 'HR', 'RBI', 'BB', 'IBB', 'SO', 'HBP', 'SH', 'SF', 'GDP', 'SB',
       'CS', 'BA', 'OBP', 'SLG', 'OPS', 'mlb_ID'],
      dtype='object')

In [85]:
import statsapi

In [273]:
player_test = statsapi.lookup_player('Austin')
player_df = pd.DataFrame(player_test)

In [295]:
player_df.currentTeam = player_df.currentTeam.astype(str)
player_df.currentTeam

0     {'id': 136}
1     {'id': 116}
2     {'id': 135}
3     {'id': 158}
4     {'id': 119}
5     {'id': 146}
6     {'id': 143}
7     {'id': 146}
8     {'id': 110}
9     {'id': 135}
10    {'id': 116}
11    {'id': 139}
12    {'id': 143}
13    {'id': 111}
14    {'id': 136}
15    {'id': 139}
16    {'id': 113}
17    {'id': 144}
18    {'id': 115}
19    {'id': 147}
20    {'id': 137}
21    {'id': 120}
22    {'id': 110}
Name: currentTeam, dtype: object

In [191]:
# for team in player_test.currentTeam:
#     print(statsapi.lookup_team(team))
# teams = [player_test['currentTeam'] for teamid in player_test]
team_ids = [list(team['currentTeam'].values()) for team in player_test]

In [250]:
team_ids = []
for teamid in player_test:
    names = list(teamid['currentTeam'].values())
    for teamname in names:
        team_ids.append(statsapi.lookup_team(teamname))

In [271]:
final_names = []
for team in team_ids:
    for name in team:
        final_names.append(name['name'])

In [297]:
player_df = player_df.replace({'{"id"':'5'})
player_df

,boxscoreName,currentTeam,firstLastName,firstName,fullFMLName,fullLFMName,fullName,id,initLastName,lastFirstName,lastInitName,lastName,mlbDebutDate,nameFirstLast,nickName,primaryNumber,primaryPosition,useName
0,Adams,{'id': 136},Austin Adams,Austin,Austin Lance Adams,"Adams, Austin Lance",Austin Adams,613534,A Adams,"Adams, Austin","Adams, A",Adams,2017-07-15,Austin Adams,A2,63,"{'code': '1', 'abbreviation': 'P'}",Austin
1,"Adams, A",{'id': 116},Austin Adams,Austin,Austin David Adams,"Adams, Austin David",Austin Adams,542866,A Adams,"Adams, Austin","Adams, A",Adams,2014-07-12,Austin Adams,NaN,50,"{'code': '1', 'abbreviation': 'P'}",Austin
2,"Allen, A",{'id': 135},Austin Allen,Austin,Austin Michael Allen,"Allen, Austin Michael",Austin Allen,664119,A Allen,"Allen, Austin","Allen, A",Allen,2019-05-11,Austin Allen,Double AA,62,"{'code': '2', 'abbreviation': 'C'}",Austin
3,Austin,{'id': 158},Tyler Austin,Christopher,Christopher Tyler Austin,"Austin, Christopher Tyler",Tyler Austin,592122,T Austin,"Austin, Tyler","Austin, T",Austin,2016-08-13,Tyler Austin,Ta,29,"{'code': '3', 'abbreviation': '1B'}",Tyler
4,"Barnes, A",{'id': 119},Austin Barnes,Austin,Austin Scott Barnes,"Barnes, Austin Scott",Austin Barnes,605131,A Barnes,"Barnes, Austin","Barnes, A",Barnes,2015-05-24,Austin Barnes,Sam,15,"{'code': '2', 'abbreviation': 'C'}",Austin
5,Brice,{'id': 146},Austin Brice,Austin,Austin Robert Brice,"Brice, Austin Robert",Austin Brice,592169,A Brice,"Brice, Austin","Brice, A",Brice,2016-08-12,Austin Brice,Bear,37,"{'code': '1', 'abbreviation': 'P'}",Austin
6,"Davis, A",{'id': 143},Austin Davis,Austin,Austin Richard Davis,"Davis, Austin Richard",Austin Davis,656354,A Davis,"Davis, Austin","Davis, A",Davis,2018-06-20,Austin Davis,Big Fudge,54,"{'code': '1', 'abbreviation': 'P'}",Austin
7,Dean,{'id': 146},Austin Dean,Austin,Austin James Dean,"Dean, Austin James",Austin Dean,621573,A Dean,"Dean, Austin","Dean, A",Dean,2018-08-15,Austin Dean,NaN,44,"{'code': '7', 'abbreviation': 'LF'}",Austin
8,Hays,{'id': 110},Austin Hays,Austin,Austin Hays,"Hays, Austin",Austin Hays,669720,A Hays,"Hays, Austin","Hays, A",Hays,2017-09-07,Austin Hays,NaN,21,"{'code': '9', 'abbreviation': 'RF'}",Austin
9,Hedges,{'id': 135},Austin Hedges,Austin,Austin Charles Hedges,"Hedges, Austin Charles",Austin Hedges,595978,A Hedges,"Hedges, Austin","Hedges, A",Hedges,2015-05-04,Austin Hedges,Hedgey,18,"{'code': '2', 'abbreviation': 'C'}",Austin
10,"Hicks, J",{'id': 116},John Hicks,John,John Austin Hicks,"Hicks, John Austin",John Hicks,543308,J Hicks,"Hicks, John","Hicks, J",Hicks,2015-08-29,John Hicks,Jazz,55,"{'code': '2', 'abbreviation': 'C'}",John
11,Meadows,{'id': 139},Austin Meadows,Austin,Austin Wade Meadows,"Meadows, Austin Wade",Austin Meadows,640457,A Meadows,"Meadows, Austin","Meadows, A",Meadows,2018-05-18,Austin Meadows,Meads,17,"{'code': '9', 'abbreviation': 'RF'}",Austin
12,"Miller, B",{'id': 143},Brad Miller,Bradley,Bradley Austin Miller,"Miller, Bradley Austin",Brad Miller,543543,B Miller,"Miller, Brad","Miller, B",Miller,2013-06-28,Brad Miller,J. Windermere,33,"{'code': '4', 'abbreviation': '2B'}",Brad
13,Moreland,{'id': 111},Mitch Moreland,Mitchell,Mitchell Austin Moreland,"Moreland, Mitchell Austin",Mitch Moreland,519048,M Moreland,"Moreland, Mitch","Moreland, M",Moreland,2010-07-29,Mitch Moreland,2-Bags,18,"{'code': '3', 'abbreviation': '1B'}",Mitch
14,"Nola, Au",{'id': 136},Austin Nola,Austin,Austin Kyle Nola,"Nola, Austin Kyle",Austin Nola,543592,A Nola,"Nola, Austin","Nola, A",Nola,2019-06-16,Austin Nola,NaN,23,"{'code': '3', 'abbreviation': '1B'}",Austin
15,Pruitt,{'id': 139},Austin Pruitt,Austin,Austin Daniel Pruitt,"Pruitt, Austin Daniel",Austin Pruitt,643493,A Pruitt,"Pruitt, Austin","Pruitt, A",Pruitt,2017-04-02,Austin Pruitt,Pruman,45,"{'code': '1', 'abbreviation': 'P'}",Austin
16,Reed,{'id': 113},Cody Reed,Cody,Cody Austin Reed,"Reed, Cody Austin",Cody Reed,642003,C Reed,"Reed, Cody","Reed, C",Reed,2016-06-18,Cody Reed,NaN,23,"{'code': '1', 'abbreviation': 'P'}",Cody
17,"Riley, A",{'id': 144},Austin Riley,Michael,Michael Austin Riley,"Riley, Michael Austin",Austin Riley,663586,A Riley,"Riley, Austin","Riley, A",Riley,2019-05-15,Austin Riley,Ocho,27,"{'code': '7', 'abbreviation': 'LF'}",Austin
18,Rodgers,{'id': 115},Brendan Rodgers,Brendan,Brendan Austin Rodgers,"Rodgers, Brendan Austin",Brendan Rodgers,663898,B Rodgers,"Rodgers, Brendan","Rodgers, B",Rodgers,2019-05-17,Brendan Rodgers,NaN,7,"{'code': '4', 'abbreviation': '2B'}",Brendan
19,Romine,{'id': 147},Austin Romine,Austin,Austin Allen Romine,"Romine, Austin Allen",Austin Romine,519222,A Romine,"Romine, Austin","Romine, A",Romine,2011-09-11,Austin Romine,Ro,28,"{'code': '2', 'abbreviation': 'C'}",Austin
20,Slater,{'id': 137},Austin Slater,Austin,Austin Thomas Slater,"Slater, Austin Thomas",Austin Slater,596103,A Slater,"Slater, Austin","Slater, A",Slater,2017-06-02,Austin Slater,AC,53,"{'code': '7', 'abbreviation': 'LF'}",Austin
21,Voth,{'id': 120},Austin Voth,Austin,Austin Lee Voth,"Voth, Austin Lee",Austin Voth,608723,A Voth,"Voth, Austin","Voth, A",Voth,2018-07-14,Austin Voth,NaN,50,"{'code': '1', 'abbreviation': 'P'}",Austin
22,Wynns,{'id': 110},Austin Wynns,Robert,Robert Austin Wynns,"Wynns, Robert Austin",Austin Wynns,642851,A Wynns,"Wynns, Austin","Wynns, A",Wynns,2018-06-05,Austin Wynns,Winnie,61,"{'code': '2', 'abbreviation': 'C'}",Austin

In [299]:
player_df = player_df.drop('currentTeam', axis=1)
player_df['Team'] = final_names

In [303]:
player_df.columns

Index(['boxscoreName', 'firstLastName', 'firstName', 'fullFMLName',
       'fullLFMName', 'fullName', 'id', 'initLastName', 'lastFirstName',
       'lastInitName', 'lastName', 'mlbDebutDate', 'nameFirstLast', 'nickName',
       'primaryNumber', 'primaryPosition', 'useName', 'Team'],
      dtype='object')

In [306]:
player_df[['firstName', 'lastName','nickName','Team','primaryNumber','primaryPosition','mlbDebutDate']]

,firstName,lastName,nickName,Team,primaryNumber,primaryPosition,mlbDebutDate
0,Austin,Adams,A2,Seattle Mariners,63,"{'code': '1', 'abbreviation': 'P'}",2017-07-15
1,Austin,Adams,NaN,Detroit Tigers,50,"{'code': '1', 'abbreviation': 'P'}",2014-07-12
2,Austin,Allen,Double AA,San Diego Padres,62,"{'code': '2', 'abbreviation': 'C'}",2019-05-11
3,Christopher,Austin,Ta,Milwaukee Brewers,29,"{'code': '3', 'abbreviation': '1B'}",2016-08-13
4,Austin,Barnes,Sam,Los Angeles Dodgers,15,"{'code': '2', 'abbreviation': 'C'}",2015-05-24
5,Austin,Brice,Bear,Miami Marlins,37,"{'code': '1', 'abbreviation': 'P'}",2016-08-12
6,Austin,Davis,Big Fudge,Philadelphia Phillies,54,"{'code': '1', 'abbreviation': 'P'}",2018-06-20
7,Austin,Dean,NaN,Miami Marlins,44,"{'code': '7', 'abbreviation': 'LF'}",2018-08-15
8,Austin,Hays,NaN,Baltimore Orioles,21,"{'code': '9', 'abbreviation': 'RF'}",2017-09-07
9,Austin,Hedges,Hedgey,San Diego Padres,18,"{'code': '2', 'abbreviation': 'C'}",2015-05-04
10,John,Hicks,Jazz,Detroit Tigers,55,"{'code': '2', 'abbreviation': 'C'}",2015-08-29
11,Austin,Meadows,Meads,Tampa Bay Rays,17,"{'code': '9', 'abbreviation': 'RF'}",2018-05-18
12,Bradley,Miller,J. Windermere,Philadelphia Phillies,33,"{'code': '4', 'abbreviation': '2B'}",2013-06-28
13,Mitchell,Moreland,2-Bags,Boston Red Sox,18,"{'code': '3', 'abbreviation': '1B'}",2010-07-29
14,Austin,Nola,NaN,Seattle Mariners,23,"{'code': '3', 'abbreviation': '1B'}",2019-06-16
15,Austin,Pruitt,Pruman,Tampa Bay Rays,45,"{'code': '1', 'abbreviation': 'P'}",2017-04-02
16,Cody,Reed,NaN,Cincinnati Reds,23,"{'code': '1', 'abbreviation': 'P'}",2016-06-18
17,Michael,Riley,Ocho,Atlanta Braves,27,"{'code': '7', 'abbreviation': 'LF'}",2019-05-15
18,Brendan,Rodgers,NaN,Colorado Rockies,7,"{'code': '4', 'abbreviation': '2B'}",2019-05-17
19,Austin,Romine,Ro,New York Yankees,28,"{'code': '2', 'abbreviation': 'C'}",2011-09-11
20,Austin,Slater,AC,San Francisco Giants,53,"{'code': '7', 'abbreviation': 'LF'}",2017-06-02
21,Austin,Voth,NaN,Washington Nationals,50,"{'code': '1', 'abbreviation': 'P'}",2018-07-14
22,Robert,Wynns,Winnie,Baltimore Orioles,61,"{'code': '2', 'abbreviation': 'C'}",2018-06-05

In [188]:
statsapi.player_stat_data(592169,group='[pitching]', type='season')

{'id': 592169,
 'first_name': 'Austin',
 'last_name': 'Brice',
 'active': True,
 'current_team': 'Miami Marlins',
 'position': 'P',
 'nickname': 'Bear',
 'last_played': None,
 'mlb_debut': '2016-08-12',
 'bat_side': 'Right',
 'pitch_hand': 'Right',
 'stats': [{'type': 'season',
   'group': 'pitching',
   'stats': {'gamesPlayed': 36,
    'gamesStarted': 0,
    'groundOuts': 42,
    'airOuts': 49,
    'runs': 21,
    'homeRuns': 7,
    'strikeOuts': 46,
    'baseOnBalls': 18,
    'intentionalWalks': 2,
    'hits': 37,
    'avg': '.214',
    'atBats': 173,
    'obp': '.312',
    'slg': '.364',
    'ops': '.676',
    'caughtStealing': 0,
    'stolenBases': 2,
    'stolenBasePercentage': '1.000',
    'groundIntoDoublePlay': 1,
    'numberOfPitches': 779,
    'era': '3.43',
    'inningsPitched': '44.2',
    'wins': 1,
    'losses': 0,
    'saves': 0,
    'saveOpportunities': 1,
    'holds': 7,
    'earnedRuns': 17,
    'whip': '1.23',
    'battersFaced': 199,
    'gamesPitched': 36,
    'completeGames': 0,
    'shutouts': 0,
    'strikes': 502,
    'strikePercentage': '64.4',
    'hitBatsmen': 7,
    'balks': 0,
    'wildPitches': 2,
    'pickoffs': 0,
    'groundOutsToAirouts': '0.86',
    'winPercentage': '1.000',
    'pitchesPerInning': '17.4',
    'gamesFinished': 10,
    'strikeoutWalkRatio': '2.56',
    'strikeoutsPer9Inn': '9.27',
    'walksPer9Inn': '3.63',
    'hitsPer9Inn': '7.46',
    'runsScoredPer9': '5.44',
    'homeRunsPer9': '1.41',
    'inheritedRunners': 16,
    'inheritedRunnersScored': 6}}]}

In [189]:
print( statsapi.linescore(565997) )

Final    1 2 3 4 5 6 7 8 9  R   H   E
Phillies 1 0 0 0 0 0 0 3 2  6   10  0
Mets     0 0 0 0 0 0 0 0 0  0   6   3

In [ ]:
stat